on: push
name: 🚀 Deploy API Engine on push
jobs:
  api-engine-deploy:
    name: 🎉 Private Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - name: Composer install
      run: composer update
    - name: 📂 Private Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: holydemo.com
        username: u483864572.holydemo_ftp_admin
        password: ${{secrets.FTP_PASSWORD}}
        port: 21
        server-dir : / 
        exclude: |
          **/.git*
          **/.git*/**
          **/public/**
          **/vendor/**
          **/.env*
    - name: 📂 Server php file Sync
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: holydemo.com
        username: u483864572.holydemo_ftp_admin
        password: ${{secrets.FTP_PASSWORD}}
        port: 21
        local-dir: ./prod_files/
        server-dir : /vendor/laravel/framework/src/Illuminate/Foundation/resources/
    - name: 📂 Public Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: holydemo.com
        username: u483864572.holydemo_ftp_admin
        password: ${{secrets.FTP_PASSWORD}}
        port: 21
        server-dir : /public_html/ 
        local-dir : ./public/


