on: push
name: 🚀 Deploy on push
jobs:
  private-deploy:
    name: 🎉 Private Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - name: Composer install
      run: composer update
